#!/bin/python
try:
    import rich, os, tempfile, argparse, sys, logging, re, pyperclip
    from pathlib import Path
    from rich.text import Text
except ImportError as e:
    print(f"Import error: {e}")

class IndexOutOfBounds(Exception):
    """Handles out of bound error"""
    pass

class BasicFileCheck(Exception):
    """Handles file error like missing file"""
    pass

class SecurityAlert(Exception):
    """Handles all security threats"""
    pass

class Note:
    def __init__(self, file_name):
        if file_name == None:
            pass
        else:
            self.base_dir = Path("~/.config/note").expanduser().resolve()
            requested_path = (self.base_dir / file_name).resolve()
            self.full_path = requested_path
            self._security_logging_system()
            if not str(requested_path).startswith(str(self.base_dir)):
                self.security_log.warning(f"CRITICAL : Path traversal was detected at {self.full_path}")
                raise SecurityAlert("Path traversal has been detected. Common don't try to hack someone  ⎛⎝( ` ᢍ ´ )⎠⎞ᵐᵘʰᵃʰᵃ")
        self.MAX_LINE = 1000
        self.MAX_INPUT = 10 * 1024 * 1024

    def _security_logging_system(self):
        try:
            self.security_log = logging.getLogger("security")
            self.security_log.setLevel(logging.INFO)
            sec_handler = logging.FileHandler(self.base_dir / ".security_audit.log")
            sec_handler.setFormatter(logging.Formatter('%(asctime)s: %(message)s'))
            self.security_log.addHandler(sec_handler)
        except FileNotFoundError as e:
            self.full_path.parent.mkdir(parents=True, exist_ok=True)
            self._security_logging_system()
    def check_note(self):
        if not self.full_path.exists():
            try:
                rich.print("[bold green] (+) File doesn't exists. Do you want to create a new one: [bold green]", end="")
                choice = input("y or n: ")
                if choice == "n":
                    sys.exit(0)
                self.create_a_file()
                return True
            except Exception as e:
                raise BasicFileCheck(f"Failed to re create a file: {e}")
        if not self.full_path.is_file():
            raise BasicFileCheck('File is not a file. Keep up the good work.')
        if self.full_path.is_symlink():
            self.security_log.warning(f"HIGH : Symbolic link has been detected in {self.full_path}")
            raise SecurityAlert("Symbolic link has been detected. Aborting.")
        return True
    
    def create_a_file(self):
        try:
            self.full_path.parent.mkdir(parents=True, exist_ok=True)
            self.full_path.touch()
            return True
        except Exception as e:
            rich.print(f"[bold red] (!) Wow error here in create_a_file: {e} [bold red]")
            return False

    def write_file(self, text):
        self.check_note()
        if len(text) > self.MAX_LINE:
            self.security_log.warning(f"MEDIUM : Too high of input, Potential buffer/DDoS attack")
            raise SecurityAlert("Too high of input, Potential buffer/DDoS attack")
        if self.full_path.stat().st_size > self.MAX_INPUT:
            raise BasicFileCheck("File size limit reached.")
        with open(self.full_path, 'a') as f:
            f.write(f"{text}\n")
        return True
        
    def read_file(self, with_index):
        self.check_note()
        with open(self.full_path, "r") as f:
            for index, line in enumerate(f, 1):
                if with_index:
                    print(f'{index}. {line.rstrip('\n')}')
                else:
                    print(line.strip('\n'))
        return True
        
    def delete_entry(self, index):
        try:
            self.check_note()
            if index < 0:
                raise IndexOutOfBounds(f"Index {index} is out of bounds. Please enter above 0")            
            if index == 0:
                rich.print("[bold red] Do you want to remove all the content of file, ", end='')
                choice = input("y or n: ")
                if choice == "n":
                    return False
                with open(self.full_path, 'w'):
                    pass
                rich.print("[bold green] (+) All contents removed from the file")
                return True            
            fd, temp_path = tempfile.mkstemp(dir=self.base_dir, text=True) 
            with os.fdopen(fd, 'w') as tmp_file:
                with open(self.full_path, "r") as f:
                    for i, line in enumerate(f, 1):
                        if i == index:
                            continue
                        tmp_file.write(line)
            os.replace(temp_path, self.full_path)
            return True
        except IndexOutOfBounds as e:
            raise e
        except Exception as e:
            if 'temp_path' in locals() and os.path.exists(temp_path):
                os.remove(temp_path)
            raise e
        
    def append_entry(self, text, index):
        try:
            self.check_note()
            if index < 1:
                raise IndexOutOfBounds(f"Index {index} is out of bounds. Please enter above 0")
            fd, temp_path = tempfile.mkstemp(dir=self.base_dir, text=True)  
            formatted_text = f"{text}\n"
            with os.fdopen(fd, 'w') as tmp_file:
                with open(self.full_path, 'r') as f:
                    for i, line in enumerate(f, 1):
                        if i == index:
                            tmp_file.write(formatted_text)
                            continue
                        tmp_file.write(line)
            os.replace(temp_path, self.full_path)
            return True
        except IndexOutOfBounds as e:
            raise e
        except Exception as e:
            if 'temp_path' in locals() and os.path.exists(temp_path):
                os.remove(temp_path)
            raise e
        
    def insert_entry(self, text, index):
        try:
            self.check_note()
            if index < 1:
                raise IndexOutOfBounds(f"Index {index} is out of bounds. Please enter above 0")
            fd, temp_path = tempfile.mkstemp(dir=self.base_dir, text=True)  
            formatted_text = f"{text}\n"
            with os.fdopen(fd, 'w') as tmp_file:
                with open(self.full_path, 'r') as f:
                    found = False
                    for i, line in enumerate(f, 1):
                        if i == index:
                            tmp_file.write(formatted_text)
                            found = True
                        tmp_file.write(line)
                if not found and index > 1:
                    tmp_file.write(formatted_text)
            os.replace(temp_path, self.full_path)
            return True
        except IndexOutOfBounds as e:
            raise e
        except Exception as e:
            if 'temp_path' in locals() and os.path.exists(temp_path):
                os.remove(temp_path)
            raise e
        
    def search_entry(self, text):
        try:
            self.check_note()
            found = False
            with open(self.full_path, "r") as f:
                for i, line in enumerate(f, 1):
                    if re.search(text, line, re.IGNORECASE):
                        found = True
                        temp_line = Text(line)
                        temp_line.highlight_regex(text, style="bold magenta underline")
                        rich.print(f"[bold green] Line {i}:[/bold green]", end="")
                        rich.print(temp_line, end="")
            if not found:
                rich.print(f"[bold red] (!) No matches found for: {text}")
                return False
        except Exception as e:
            # rich.print(f'[bold red] (!) Parlay has been given by error in search_entry: {e}')
            raise e
        
    def copy_lines(self, with_index):
        try:
            lines = []
            self.check_note()
            with open(self.full_path, "r") as f:
                for index, line in enumerate(f, 1):
                    if with_index:
                        start_line, end_line = with_index.split("-")
                        if index >= int(end_line):
                            break
                        if index >= int(start_line):
                            lines.append(line)
                    else:
                        lines.append(line)
            pyperclip.copy("".join(lines))
        except Exception as e:
            raise e
        
        
    def search_files(self):
        try:
            files = [p.name for p in self.base_dir.glob("*") if p.is_file()]
            files.sort()
            for file in files:
                print(file)
        except Exception as e:
            raise e
            
    def erase_file(self): 
        try:
            if not self.full_path.exists():
                raise BasicFileCheck("If you want to delete a file then create one first ദ്ദി(˵ •̀ ᴗ - ˵ ) ✧")
            self.full_path.unlink()
        except Exception as e:
            raise e
        
if __name__ == "__main__":
    try:
        parser = argparse.ArgumentParser(description="This is an note taking application.")
        parser.add_argument("file", nargs="?", default="note.txt", help="Enter name of note here.")
        subparsers = parser.add_subparsers(dest="command")

        list_parser = subparsers.add_parser("list", help="Lists all entries in the file")
        list_parser.add_argument("-i", "--index", action="store_true", help="Lists all entries in the file with indexes")

        add_parser = subparsers.add_parser("write", help="Writes down a entry")
        add_parser.add_argument("content", help="Write down the stuff you wanna write")

        delete_parser = subparsers.add_parser("delete", help="Deletes a entry in the list")
        delete_parser.add_argument("content", help="Write the index of the list you want to delete")
        delete_parser.add_argument("-a", "--all", action="store_true", help="Removes all the content in the file")

        append_parser = subparsers.add_parser("append", help="Changes the required entry")
        append_parser.add_argument("content", help="Write the content that will be kept in the entry instead")
        append_parser.add_argument("-i", "--index", help="Write the index that needs to be changed")

        insert_parser = subparsers.add_parser("insert", help="Inserts entry in the note which out removing anything else")
        insert_parser = subparsers.add_parser("content", help="Write entry to be added to the note")

        search_parser = subparsers.add_parser("search", help="Searches for some patterns")
        search_parser.add_argument("content", help="Write what should be searched for")

        list_parser = subparsers.add_parser("ls", help="lists all the files that has been created")
        erase_parser = subparsers.add_parser("destroy", help="Removes the file completely")

        copy_parser = subparsers.add_parser("copy", help="Copies the content of file")
        copy_parser.add_argument("-i", "--index", help="Copies the indexed content of file")
        args = parser.parse_args()  
        note = Note(args.file or None)

        if args.command == "list":
            rich.print(f'[bold yellow] (*) Listing all the entries .... (*) [bold yellow]')
            note.read_file(args.index)
        elif args.command == "write":
            rich.print(f'[bold blue] (*) Writing the content: {args.content} (*) [bold blue]')
            note.write_file(args.content.encode('utf-8').decode('unicode_escape'))
        elif args.command == "delete":
            rich.print(f"[bold red] (*) Deleting the content: {args.content} (*) [bold red]")
            note.delete_entry(int(args.content))
        elif args.command == "append":
            rich.print(f"[bold purple] (*) Appending the content: {args.content} in index {args.index} (*) [bold purple]")
            note.append_entry(args.content.encode('utf-8').decode('unicode_escape'), int(args.index))
        elif args.command == "ls":
            rich.print(f"[bold cyan] (*) Listing all the files (*) [bold cyan]")
            note.search_files()
        elif args.command == "destroy":
            rich.print(f"[bold red] (!) Are you sure you want to remove this file, [bold red]", end="")
            choice = input("y or n: ")
            if choice == "y":
                note.erase_file()
            else:
                sys.exit(0)
        elif args.command == "search":
            rich.print(f"[bold magenta] (*) Searching for pattern now {args.content} (*) [bold magenta]")
            note.search_entry(args.content)
        elif args.command == "copy":
            rich.print(f"[bold green] (*) Copying from the file (*) [bold green]")
            note.copy_lines(args.index or None)
        logging.basicConfig(
            filename=Path("~/.config/note/.error_audit.log").expanduser(),
            level=logging.ERROR,
            format='%(asctime)s: %(message)s'
        )
    except BasicFileCheck as e:
        logging.error(f'File error: {e}')
        rich.print(f'[bold red] File error: {e} [bold red]')
        sys.exit(0)
    except SecurityAlert as e:
        rich.print(f'[bold red] Security Alert: {e} [bold red]')
        sys.exit(0)
    except IndexOutOfBounds as e:
        logging.error(f'Index error: {e}')
        rich.print(f'[bold red] (!) Index error: {e} [bold red]')
        sys.exit(0)
    except Exception as e:
        logging.error(f'Unexpected error: {e}')
        rich.print(f'[bold red] There is a huge problem, error in init: {e} [bold red]')
        sys.exit(0)